### ISSUE TITLE
Passing further options in with mapOptions

### ISSUE THREAD

**Issue by AleskiWeb** [Credera/angular-bing-maps#20]
Hi,

Working with your component here is really nice. It's kind of got everything and it seems like such a time saver.

One question I would have is, would it be possible to pass further map options to the initial set that are passed through (like zoom etc)?

There are options like "showMapTypeSelector:false" and "theme: new Microsoft.Maps.Themes.BingTheme() " that I would love to pass in but my efforts so far have been spotty at best.

Thanks in advance

**Comment by sjmorrow** [comment]
@AleskiWeb thanks for the positive feedback! Glad you like the project. We are currently in the development phase of that exact feature. If you require the feature immediately, you could try out the "develop" branch. We added an extra attribute to the parent <bing-map> directive called "options" whose argument is exactly what you are looking for. Unfortunately, bing maps requires certain attributes to be declared BEFORE the map is instantiated (like "theme" for example). Our solution to this is to have a config provider that will allow users to declare map options inside an app.config() block. We will leave this issue open until we fully implement that functionality.

For reference, we plan on setting up an [angular provider](https://docs.angularjs.org/guide/providers#provider-recipe) that the users can then inject into a config() block

**Comment by AleskiWeb** [comment]
@sjmorrow thanks for getting back to me! Yeah that sounds ace. Like you said, with the attributes being declared before the map is instantiated, I couldn't get the theme option to play nice.

However I did manage to just pass an additional attribute, probably similar to what you were talking about, for the simple options that dont need additional things declared,

I'll be sure to check out the dev branch.
