### ISSUE TITLE
Give user access to Microsoft.Maps.Map instance

### ISSUE THREAD

**Issue by sjmorrow** [Credera/angular-bing-maps#29]
To allow users to access the methods and attributes of the Microsoft.Maps.Map instance, we need to add a callback function to the <bing-map> directive that will be executed once the map has been instantiated. This callback will provide one argument to it's callee, "map" which is a reference to our Microsoft.Maps.Map instance.

This will allow them to call methods like Map.getZoom() and Map.getCenter() as requested by @AleskiWeb in #28

**Comment by sjmorrow** [comment]
Updated issue to include a callback based solution instead of a service based solution, since the user can theoretically add multiple bing-maps to a single page

**Comment by glombek** [comment]
Used like so:

<bing-map
            credentials="'AkaxzD5YOJCbIvziHVOLfm6AkeM5Z5UQ3dHS53mQzwK-6LGWnxYjAwNqfe3D4UBT'"
                center="mapOptions.center"
                zoom="mapOptions.zoom"
                mapType="mapOptions.mapType"
                callback="myMethod(map)">
            </bing-map>

**Comment by glombek** [comment]
Sorry I didn't see your suggested naming in #28. Will update that today.

**Comment by AleskiWeb** [comment]
Hi glombek, I was wondering how to implement this and I have the same solution as yourself. However, if I understand it, if I wanted to access the map zoom level, for example, would it be:

    $scope.myMethod = function(map) {
        $scope.map = map.getZoomLevel();
    };

or would it be:

    $scope.myMethod = function(map) {
        $scope.map = map
        $scope.mapZoomLevel = $scope.map.getZoomLevel()
    };

I'm having trouble actually getting the map instance to output on the page somewhere. Could you show me an example of how to actually have something like the zoom level output to the view?

**Comment by glombek** [comment]
Either of those should work fine (assuming you're running the code on my develop branch of my fork (the pull request has not been accepted yet).
I haven't tested your exact example, but I am using very similar code to get the Session Key, for example.
I will try your code later today and see if I can spot what's up.

**Comment by AleskiWeb** [comment]
So I found the issue. The controller I was calling it in was using the syntax `controller As: "map"` so when I was calling the callback with `callback="myMethod(map)"` the controller is being passed in so it was messing it all up.

**Comment by glombek** [comment]
Oh dear! That's not pretty!
I don't think there's a particularly nice way around that one unfortunately, other than aliasing the controller as something else.
Glad you resolved it though!

**Comment by sjmorrow** [comment]
@glombek I closed the PR because the change was made to the wrong file. Unfortunately, we have to include the compiled version of our source code in the repository for bower to serve it. Please reimplement this change in src/angular-bing-maps/directives/map.directive.js, and while you are in there please rename $scope.map to $scope._map to avoid the issue pointed out by @AleskiWeb

**Comment by glombek** [comment]
The issue with naming it `_map` would be that users would then have to write `on-map-ready="myMethod(_map)"` (I believe Angular maps this based on string) which may be uglier. Users are also just as likely to have a variable named `_map`.

I will, however, create a new PR in the correct location. I didn't spot this!

**Comment by sjmorrow** [comment]
Sorry, I think I was unclear. Rename the variable we use internally to _map so that the user can use the `on-map-ready="myMethod(map)"` syntax. You'll see what I mean when you dive into that file.

**Comment by sjmorrow** [comment]
Ignore me, I read @AleskiWeb comment completely wrong. Carry on!

**Comment by sjmorrow** [comment]
I had some free time, so I went ahead and copied and pasted your changes into the dev branch. This functionality is now in the develop branch and should go into master for the v0.2.0 release. Thanks for your contributions @AleskiWeb and @glombek

**Comment by glombek** [comment]
Ahh thank you @sjmorrow! I was hoping to get to it this weekend but I shan't need to worry now!
