### ISSUE TITLE
Two way bind map center

### ISSUE THREAD

**Issue by glombek** [Credera/angular-bing-maps#36]
I realize this may have some performance issues but thought it should be put up for discussion.

The directive would have to listen out for one of the viewchange events and apply this back to the center attribute.

**Comment by sjmorrow** [comment]
I think this is a great idea. Hooking into the 'viewchangeend' event provided by Microsoft should not have a significant performance impact. Now that we have a [config provider](https://github.com/Credera/angular-bing-maps/blob/develop/src/angular-bing-maps/providers/angular-bing-maps-provider.js), we could even give the user the ability to change this to the 'viewchange' event (which WOULD have a slight performance impact). Let's get the two-way binding working first, and then we will look into making it configurable. I'll leave this feature open for PRs, and if no one gets to it in the next week, I can look into making the change.

Great suggestion @glombek
