### ISSUE TITLE
Next version release?

### ISSUE THREAD

**Issue by AleskiWeb** [Credera/angular-bing-maps#37]
Hey!

I was wondering when the next tagged release was going to take place? I'm currently fairly dependant on some of the features in the development branch, which is fine for now because I'm just working locally but if anyone was to get my project and bower install, there would be some problems :P

**Comment by sjmorrow** [comment]
I think we are in a good place to do a v0.2.0 release. I'll try and get to that today and let you know when it's done.

**Comment by sjmorrow** [comment]
Done. We are live with v0.2.0 in bower, which contains all the latest changes.
