### ISSUE TITLE
MIT License?

### ISSUE THREAD

**Issue by smlombardi** [Credera/angular-bing-maps#38]
It would be more helpful for us if you chose a "standard" open source license, such as MIT or Apache. My company forbids us to use open source software without a standard license.  Any chance you could please move to an MIT license?

**Comment by sjmorrow** [comment]
I will ask the powers that be about transferring to a new license type. The current license is what I was told to use, so I will need to seek approval first.

I am admittedly ignorant of the differences in licenses, so I apologize for not being able to make this change immediately.

**Comment by sjmorrow** [comment]
I just checked our (LICENSE)[https://github.com/Credera/angular-bing-maps/blob/master/LICENSE] and it is indeed the MIT License. Closing this issue.
