### ISSUE TITLE
i got error provider.

### ISSUE THREAD

**Issue by ghost** [Credera/angular-bing-maps#46]
Error: [$injector:unpr] Unknown provider: eProvider <- e <- bingMapDirective

please help me.

**Comment by sjmorrow** [comment]
Sorry for the late response. Can you give a watered down version of your code and the tools you are using in your project? For example, are you using any sort of minification / uglification / obfuscation tools in your build process? You are the second person to report this issue and I am having a hard time reproducing it.

**Comment by sjmorrow** [comment]
This should hopefully be addressed with dc33a1063.

Closing issue for now until someone reports otherwise. This change will be available in any version after 0.2.1
