### ISSUE TITLE
What pushpin was clicked in ng-repeat

### ISSUE THREAD

**Issue by sambengtson** [Credera/angular-bing-maps#48]
I'm trying to figure out how I can use the click event in an ng-repeat list to get the pushpin that was clicked by the user.  I am aware of the events click handler but I'm having a hard time getting that to perform as I would like.  I would like to be able to use ng-click so I can control the function parameters but this does not seem possible.  Any ideas?

**Comment by akoutmos** [comment]
I had this exact problem about a month ago. I made a PR for my solution to this #47. 

I'm not sure what the state of this project is given that PRs have been around for a little while. I have forked the repo with my changes and #45 in my develop branch. I would like to get these changes back into this repo, but you are free to check out my fork in the mean time.

**Comment by sjmorrow** [comment]
Sorry for missing that PR @akoutmos. I have been unable to maintain this project as much as I would like to. I just did a quick code review and merged it into the develop branch. Feature will go into the next release.

Thanks for your contribution

**Comment by sjmorrow** [comment]
@sambengtson You can either pull the latest from dev to get @akoutmos change, which added a "data" field to the pushpin model. Or you can do what I was doing in my apps, use the "track-by" directive on the pushpin. Just pass in some unique ID string to this "track-by" directive, and that ID will come back in the pushpin event as `event.target.trackBy`. I use this ID to lookup the pushpin's corresponding data in my application

**Comment by sambengtson** [comment]
Thanks guys.  Looks good to me.
